// Mocks generated by Mockito 5.4.6 from annotations
// in attend/test/features/auth/domain/usecases/student_signup_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:attend/features/auth/domain/entities/lecturer_entity.dart'
    as _i7;
import 'package:attend/features/auth/domain/entities/student_entity.dart'
    as _i6;
import 'package:attend/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:attend/global/error/failures.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> studentSignUp(
    _i6.StudentEntity? studentEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#studentSignUp, [studentEntity]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#studentSignUp, [studentEntity]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.StudentEntity>> studentLogin(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#studentLogin, [email, password]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.StudentEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.StudentEntity>(
                    this,
                    Invocation.method(#studentLogin, [email, password]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.StudentEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.LecturerEntity>> lecturerSignUp(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lecturerSignUp, [email, password]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.LecturerEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.LecturerEntity>(
                    this,
                    Invocation.method(#lecturerSignUp, [email, password]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.LecturerEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.LecturerEntity>> lecturerLogin(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lecturerLogin, [email, password]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.LecturerEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.LecturerEntity>(
                    this,
                    Invocation.method(#lecturerLogin, [email, password]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.LecturerEntity>>);
}
